# Generated by Django 6.1.1 on 2026-09-27 03:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('date_saved', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date saved')),
                ('is_learned', models.BooleanField(default=False)),
            ],
        ),
    ]
